# Streamlit Configuration
# Theme matches mockup design: https://ma3u.github.io/neo4j-agentframework/

[theme]
# Base theme
base = "dark"

# Primary colors (from mockup)
primaryColor = "#FF4B4B"          # Accent red (buttons, highlights)
backgroundColor = "#0E1117"        # Main background
secondaryBackgroundColor = "#262730"  # Cards, sidebar
textColor = "#FAFAFA"              # Primary text

# Font
font = "sans serif"

[server]
# Server configuration
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
# Browser configuration
gatherUsageStats = false

[runner]
# Performance
magicEnabled = true
fastReruns = true

[client]
# Client configuration
showErrorDetails = true
toolbarMode = "minimal"
