# Streamlit Secrets Configuration
# For local development outside Docker

LOCAL_DEV = false
RAG_API_URL = "http://localhost:8000"
NEO4J_URI = "bolt://localhost:7687"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "password"
